update

diff --git a/.github/actions/linux-e2etest/action.yml b/.github/actions/linux-e2etest/action.yml
--- a/.github/actions/linux-e2etest/action.yml
+++ b/.github/actions/linux-e2etest/action.yml
@@ -39,6 +39,12 @@ runs:
         ZE_AFFINITY_MASK: ${{ steps.get-runner-infos.outputs.ZE_AFFINITY_MASK }}
       shell: bash -eo pipefail {0}
       run: |
+        # Set test environment
+        if [ "${XPU_ONEAPI_PATH}" != "" ];then
+          source "${WORKSPACE}/torch-xpu-ops/.github/scripts/env.sh" || {
+            echo "Warning: Failed to source environment script"
+          }
+        fi
         # Configuration and setup
         SCRIPT_DIR="${{ github.workspace }}/.github/scripts"
         TARGET_DIR="${{ github.workspace }}/pytorch"
